### ISSUE TITLE
linuxtools uses deprecated (and now removed) API

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-linuxtools/org.eclipse.linuxtools#112]
https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/ae7fff3b50d7fc5630661c9dbabdb8f16fe3a805/containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/launch/RunImagePortsTab.java#L161

https://github.com/eclipse-platform/eclipse.platform.ui/pull/323 removed the deprecated class [`org.eclipse.jface.databinding.viewers.ViewersObservables`](https://github.com/eclipse-platform/eclipse.platform.ui/blob/5d771875d5adeb00b82cebbd07bfba392d44e7cf/bundles/org.eclipse.jface.databinding/src/org/eclipse/jface/databinding/viewers/ViewersObservables.java) <-- link to file before it was deleted so you can read the `@deprecated` instructions.

xref: https://github.com/eclipse-cdt/cdt/issues/73 which is the same issue for CDT.

If linuxtools fixes this first it will give me some guidance on fixing this. Likewise if CDT fixes it first I hope https://github.com/eclipse-cdt/cdt/issues/73 is useful.

**Comment by akurtakov** [comment]
This is fixed via https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/commit/066eb7adfaa0c5f94d74f23670050de7e5892a30 but we can't throw out new build due to build issues.

**Comment by akurtakov** [comment]
Builds are regularly produced now so I close this now.
