### ISSUE TITLE
Docker Tooling - "Execute Shell" option for a container isn't opening a interactive shell in Mac

### ISSUE THREAD

**Issue by spdnitian** [eclipse-linuxtools/org.eclipse.linuxtools#129]
When trying to launch a shell for a running container by selecting "Execute Shell" option from the container context menu, it is launching a non-interactive shell. The shell doesn't respond any input from the keyboard. It remains a blank shell.

**Processor**:
Intel Core i7

**OS**:
macOS Montery 12.6.1 (21G217)

**Eclipse:** 
Version: 2022-09 (4.25.0)
Build id: 20220908-1902

**Docker Tooling**:
5.8.0.202209062047

**Steps to reproduce**

1. Run any docker container from Docker Explorer.
2. Right click on the container.
3. Click "Execute Shell".
4. Type any command/text in the opened shell.

**Expected behaviour:**
The command/text should be typed in the opened shell.

**Actual Behaviour:**
The shell remains blank. The command doesn't get typed into the shell.

**Comment by akurtakov** [comment]
So this is Docker desktop issue and not this plugin's fault?

**Comment by akurtakov** [comment]
No reply from reporter in more than a year, closing.
