### ISSUE TITLE
If no tag is given DockerConnection.pullImage pulls all tags

### ISSUE THREAD

**Issue by cmorty** [eclipse-linuxtools/org.eclipse.linuxtools#140]
This is kind of unexpected and should be documented

Reproduce: 
* make sure you have no alpine image on your system
* Pull "alpine"

**Comment by akurtakov** [comment]
What is the status of this one? I see a fix in CDT repo?

**Comment by cmorty** [comment]
@akurtakov Seems like I fixed it. :) I've been working on other projects, so my brain started clearing out suff. I'll close it. Someone else can complain, if it's not fixed. :)
