### ISSUE TITLE
Request: Provide public access to docker.[...].ImageNameValidator

### ISSUE THREAD

**Issue by cmorty** [eclipse-linuxtools/org.eclipse.linuxtools#143]
It would be nice to have access to the validator. E.g. to fix things like https://github.com/eclipse-cdt/cdt/pull/181

Also it feels like it should go into core. :)

I'm willing to make a PR, but having some guidelines where to put it and how to best expose it would be nice.

**Comment by akurtakov** [comment]
If you're still interested in opening a PR, we will figure it out. Sorry for the very late reply.

**Comment by cmorty** [comment]
Sorry. Currently not Working on Eclipse, though there is more than enough I'd like to fix. ;) I'll reopen this in case I stumble upon it in the future.
