### ISSUE TITLE
Ask for help: Have trouble setting the target platform on Eclipse RCP IDE

### ISSUE THREAD

**Issue by baoruiqi** [eclipse-linuxtools/org.eclipse.linuxtools#167]
### Description
According to the instructions in [this page,](https://wiki.eclipse.org/Linux_Tools_Project/Getting_Involved#Target_Platform) I tried to configure the development environment on my computer. When setting the target platform, I encountered the problem as shown in the figure.

![2023-03-21_16-03](https://user-images.githubusercontent.com/128341204/226550444-2b8c86f6-3912-4241-a8b6-d140ebe61e08.png)

### Source code
latest on branch master cloned from this repo 

### System info
Linux version 5.15.0-67-generic (buildd@lcy02-amd64-116) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023

Ubuntu 22.0.4 LTS

### IDE info
Eclipse IDE for RCP and RAP Developers (includes Incubating components)
Version: 2023-03 (4.27.0)
Build id: 20230309-1520

### Java version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)

Could someone do me a favor？ @akurtakov @jjohnstn

**Comment by akurtakov** [comment]
Please try now with linuxtools-e4.28 target

**Comment by akurtakov** [comment]
If you're building Linux Tools from source you either have to install it into your running eclipse or launch a child eclipse from it to be able to use Linux Tools functionality.

**Comment by baoruiqi** [comment]
I probably have found a glitch in the gcov module, so I attempt to modify the source then build it. The child eclipse on the right  part of the figure is what I got by clicking the "Run As"  button in the development environment on the left. But the functionality is still not found.

![Screenshot from 2023-03-21 20-17-28](https://user-images.githubusercontent.com/128341204/226603939-07d537dd-459b-4301-a9c4-43e49a5b6fc1.png)

Besides, what do you mean by "installing it into your running eclipse" ?  You mean, download the linux tools plugin from the eclipse marketplace, and then modify by importing it as source project?

**Comment by akurtakov** [comment]
Ignore the "installing into your running eclipse" part, I think I understand your question now. On the Run configuration page does it report any issue when clicking "Validate Plug-ins" button?

**Comment by baoruiqi** [comment]
I select "Launch with" instead of the default "All workspace and enabled target plugins" to launch the app, then I find two items related to the reported issue,  one version of which obviously doesn't satisfy the requirement of [2.9.1, 2.10.0). So I uncheck  this item, after that the validation comes with no issue. However, the child eclipse still has no functionality of profiling. 

![image](https://user-images.githubusercontent.com/128341204/226775919-94b52525-87a8-437d-99c0-a3ebc1bc7d76.png)
