### ISSUE TITLE
Any plan to support gcov or gprof tools with prefix 

### ISSUE THREAD

**Issue by fanghuaqi** [eclipse-linuxtools/org.eclipse.linuxtools#181]
Hello,

We are using this linuxtools project to do code coverage and profiling for embedded system such as arm and riscv, but the toolchain will have a prefix such as `riscv64-unknown-elf-gprof/gcov`, but the plugin itself seems to bind with a fixed name, is it possible to let user to set it in project properites, which will make embedded development possible to use this great plugin in eclipse cdt.

Like in the embedded cdt plugin https://github.com/eclipse-embed-cdt/eclipse-plugins, it will provide prefix settings

![image](https://user-images.githubusercontent.com/1538922/236984024-828b2f4a-1778-4222-bafb-7e4a3315d450.png)

Maybe it will great to set this linux tools prefix in its configuration page, but currently it is not possible.

![image](https://user-images.githubusercontent.com/1538922/236984398-9e3ec588-d8e9-459f-bdde-d227b35f7581.png)

So to use this profiling and coverage feature in embedded software development, I have to change the gprof and gcov related binaries from its prefixed ones to unprefixed ones like this.

![image](https://user-images.githubusercontent.com/1538922/236984587-ed936977-6c2f-4b3f-9b34-3dad10ace86e.png)

Otherwise the IDE will become not-responding.

Thanks

**Comment by fanghuaqi** [comment]
Thanks for your help, we will try to take a look at it, do you have any guidance on what source files need to changes to achive it, so we can have a quick ramp up.

**Comment by akurtakov** [comment]
I forgot to answer this one, sorry! The UI part is https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/tree/master/profiling/org.eclipse.linuxtools.tools.launch.ui and from it you can see which preference and set and where it's used.

**Comment by fanghuaqi** [comment]
Thanks @akurtakov

**Comment by fanghuaqi** [comment]
@laomaolaile Could give some screenshot and idea about our changes to this tool, maybe PR could be opened to address this issue.

Thanks

**Comment by laomaolaile** [comment]
**about the toolspath**

1.  And allows path to use the Global variable of eclipse . eg: `${eclipse_home}`
2. And during the testing process, I found that the path segmentation method is ":", but in Windows it is ";", so I modified some of the code to be suitable for different environments in Windows and Linux

I added a Prefix to apply to different toolchains

![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/19726057/6a3824c4-e842-41b5-8d42-67c1ce21be4c)

**Comment by akurtakov** [comment]
Is there still interest in this one?

**Comment by fanghuaqi** [comment]
Hi @akurtakov ， the changes #205  has been merged into this repo, I think this issue is fixed, I will close it. 
Thanks
