### ISSUE TITLE
Linuxtools docker resolution problem

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-linuxtools/org.eclipse.linuxtools#232]
@akurtakov I know you are working on this at the moment, but in recent days the Eclipse CDT build breaks:

```
Error:  Cannot resolve target definition:
Error:    Software being installed: org.eclipse.linuxtools.docker.feature.feature.group 5.12.0.202307201237
Error:    Missing requirement: com.google.guava 32.1.1.jre requires 'java.package; com.google.common.util.concurrent.internal [1.0.0,2.0.0)' but it could not be found
Error:    Cannot satisfy dependency: org.eclipse.linuxtools.docker.core 5.12.0.202307201237 depends on: osgi.bundle; com.google.guava 32.1.1
Error:    Cannot satisfy dependency: org.eclipse.linuxtools.docker.feature.feature.group 5.12.0.202307201237 depends on: org.eclipse.equinox.p2.iu; org.eclipse.linuxtools.docker.core [5.12.0.202307201237,5.12.0.202307201237]
```

See PRs:
- https://github.com/eclipse-cdt/cdt/pull/470
- https://github.com/eclipse-cdt/cdt/pull/471

If you aren't done yet I will revert to latest release of linuxtools docker for now and rejoin nightly when you want me to test it out again.

**Comment by akurtakov** [comment]
There is nothing more I plan for this cycle. Maybe in the future I'll try to move docker-client to smth newer than 5.x  but I'm tired of this effort now and the main driver is moving to Maven wherever possible.

**Comment by jonahgraham** [comment]
Ok I'll dig in a little more because Linux tools docker nightly isn't resolving at the moment and there are multiple versions of guava in the repo.

**Comment by jonahgraham** [comment]
> multiple versions of guava in the repo.

This comes from the update in https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/commit/e1c13df5f7d056a3d5e4463b0d9d2ad748259a06 for guava 32.1.1 + dependency on lsp4e -> wikitext -> guava 31.1.0

**Comment by jonahgraham** [comment]
![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/679236/52c8406d-848c-4384-a368-80d0a71e00ff)

**Comment by jonahgraham** [comment]
I don't know why it has started failing for CDT - but AFAICT it looks like com.google.guava.failureaccess is not provided anywhere in the CDT target platform (anymore?)

The https://download.eclipse.org/linuxtools/updates-docker-nightly/ is in an odd state now - it republishes a seemingly random set of its dependencies, including eclipse projects like LSP4E and guava, but not dependencies of LSP4E like wikitext and tm4e.

However this does not seem to be a recent change so I am going to simply add more stuff to cdt.target to get it to work with the recent updates you (@akurtakov) did.

**Comment by jonahgraham** [comment]
I have raised https://github.com/eclipse-pde/eclipse.pde/issues/675 as it looks like there is a resolution error that the recent changes in linuxtools exposes.
