### ISSUE TITLE
Add support for syntax highlighting for Containerfile

### ISSUE THREAD

**Issue by erik-brangs** [eclipse-linuxtools/org.eclipse.linuxtools#292]
Some tools (e.g. [Buildah](https://github.com/containers/buildah/issues/1853)) support `Containerfile` as an alternative to `Dockerfile`.

It would be nice if the Eclipse Linux Tools offered syntax highlighting for `Containerfile`-

**Comment by erik-brangs** [comment]
I actually tried to implement this but I wasn't able to make it work. I looked at https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/pull/50/commits/502598e8998133d03a9b77cd58122327323c36a1 and tried to do it in a similar way.

I was only able to make it work for `Containerfile.something` but not for `Containerfile`:
```
diff --git a/containers/org.eclipse.linuxtools.docker.editor.ls/plugin.xml b/containers/org.eclipse.linuxtools.docker.editor.ls/plugin.xml
index f68b06f98d..a51f24f8a8 100644
--- a/containers/org.eclipse.linuxtools.docker.editor.ls/plugin.xml
+++ b/containers/org.eclipse.linuxtools.docker.editor.ls/plugin.xml
@@ -25,9 +25,9 @@
          point="org.eclipse.core.contenttype.contentTypes">
       <content-type
             base-type="org.eclipse.core.runtime.text"
-            file-extensions="Dockerfile,dockerfile"
-            file-names="Dockerfile"
-            file-patterns="Dockerfile.*"
+            file-extensions="Dockerfile,dockerfile,Containerfile,containerfile"
+            file-names="Dockerfile,Containerfile"
+            file-patterns="Dockerfile.*,Containerfile.*"
             id="org.eclipse.linuxtools.docker.editor.ls"
             name="Dockerfile"
             priority="normal">

```

**Comment by akurtakov** [comment]
Is Containerfile just a rename of Dockerfile ?

**Comment by erik-brangs** [comment]
Yes, it's just another name that's supposed to be more vendor-neutral.

**Comment by akurtakov** [comment]
After the build completes youl should  be able to install new dockertools from https://download.eclipse.org/linuxtools/updates-docker-nightly/ with support for Containerfile in it.

**Comment by erik-brangs** [comment]
I installed the nightly in my Eclipse installation at work and the Containerfile syntax highlighting seems to work fine.

Thank you.
