### ISSUE TITLE
What is the format of a. out file?

### ISSUE THREAD

**Issue by laomaolaile** [eclipse-linuxtools/org.eclipse.linuxtools#311]
What is the format of a. out file? If there is other data, how can a. out file be generated？

Because in my project, I have another trace that I want to use to parse out a. out file and display the results directly through org. eclipse. linuxtools

I don't know if this is feasible

Looking forward to your answer！

**Comment by jjohnstn** [comment]
Originally, unix had a format called a.out for executable files.  This differs from the executable format on Windows which have the .exe suffix.  Today, unix has switched to the Elf format for executables which is different that a.out format, however, the name of a default executable created by gcc is still named a.out.  The easiest way to generate an a.out file is using gcc or use the CDT (C/C++ Development Tools) and create a C/C++ project.  There's lots of information out there about the elf format:  e.g. https://en.wikipedia.org/wiki/Executable_and_Linkable_Format  There are also command-line tools to look at elf format (e.g. nm, readelf) which have a number of options for displaying details (e.g. demangling of variable names).  The CDT project has support for displaying some information about elf format files in the Project Explorer simply by clicking on the file.

**Comment by laomaolaile** [comment]
In the gprof tool, the. out file should not be an executable file, right? I don't know what format it is, can you please let me know.

![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/19726057/4a54047c-37db-4f52-9aac-44cbeb7babea)

**Comment by jjohnstn** [comment]
Sorry, misread a .out as a.out.  gmon.out is not an executable file.  It is a special format file designed for use with the gprof tool.  One uses the -pg gcc compiler option and when run, the execution creates this separate output file containing profile info.  Information about the format can be found in the binutils project under the gprof directory.

**Comment by jjohnstn** [comment]
Closing this as question has been answered and this is not a specific Linux Tools issue.

**Comment by TommyMurphyTM1234** [comment]
> In the gprof tool, the [gprof].out file should not be an executable file, right? I don't know what format it is, can you please let me know.

* https://github.com/bminor/binutils-gdb/blob/97f2a34ed1d255ea301f858b31c0fbe75da1c4f6/gprof/README#L370-L384
