### ISSUE TITLE
Link to Jenkins job is not working in PR.

### ISSUE THREAD

**Issue by Torbjorn-Svensson** [eclipse-linuxtools/org.eclipse.linuxtools#38]
While waiting for the build result of #37, I decided to try the link to the Jenkins job by clicking on "Details" next to the Jenkins line in the browser.
At the time of this report, the link points to https://ci.eclipse.org/linuxtools/job/linuxtools/job/PR-37/display/redirect, but clicking on that link and signing in just gives:

> Access Denied
> user@host.tld is missing the Job/Build permission

I suppose the link should work regardless if you are a committer on the linuxtools project or just a regular contributor. I'm not stating that all contributors should have build permission, but I suppose the link could point to https://ci.eclipse.org/linuxtools/job/linuxtools/job/PR-37/1/ or something similar.
Obviously, I've masked my email to avoid spambots from collecting it (user@host.tld is my real address).

**Comment by akurtakov** [comment]
As time has passed there seems to not be anyone interested in working on this one. We would happily accept help on this one though. Feel free to reopen and help us.

**Comment by akurtakov** [comment]
> First step here; does the link work for you @akurtakov? As the PR #37 is merged since a long time, maybe you can try this (a PR that you created not so long ago): https://ci.eclipse.org/linuxtools/job/linuxtools/job/PR-67/display/redirect

^^ works for me.

> 
> Looking at https://www.jenkins.io/doc/book/using/using-credentials/#adding-new-global-credentials gives the impression that the credentials part is not something you define in a Jenkinsfile, but rather on the Jenkins instance itself.

Unfortunately there is no "Manage jenkins" visible for me so I opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1472 for Eclipse team to guide us.

**Comment by akurtakov** [comment]
So the helpdesk issue has been closed claiming that fix in jenkins is needed. Closing this one as nothing can be done on Linux Tools side.
