### ISSUE TITLE
Wiki article is outdated after the github migration

### ISSUE THREAD

**Issue by Torbjorn-Svensson** [eclipse-linuxtools/org.eclipse.linuxtools#39]
The wiki article at https://wiki.eclipse.org/Linux_Tools_Project/Getting_Involved is outdated after the migration from Eclipse hosted infra to github.
As I'm not part of the project and do not know how you want to proceed, now that you've migrated to github, I think it would be best if someone with the required insight updates the wiki article to describe the new process of sending patches etc. and also update the repository location.

**Comment by akurtakov** [comment]
I have done initial edit of the wiki pages to allow migration to happen. Overall wiki is scheduled for removal by Eclipse Foundation so we need decent content in README.md in the repo directly.

**Comment by akurtakov** [comment]
I actually consider this done. Please feel free to adjust if smth is missing or reopen this one.
