### ISSUE TITLE
The latest contribution to SimRel has unsigned content:

### ISSUE THREAD

**Issue by merks** [eclipse-linuxtools/org.eclipse.linuxtools#399]
These reports indicate that the content is neither jar signed nor PGP signed except where that content comes signed from somewhere else:

- https://download.eclipse.org/oomph/archive/reports-extra/linuxtools-update-2024-09-rc1/download.eclipse.org/linuxtools/update-2024-09-rc1/index.html
- https://download.eclipse.org/oomph/archive/reports-extra/linuxtools-update-2024-09-docker-rc1/download.eclipse.org/linuxtools/update-2024-09-docker-rc1/index.html

**Comment by akurtakov** [comment]
This is due to https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/b069ec118e008248087f39e484b142d98c9e5e8b/Jenkinsfile#L72 which signs only master build and Jeff did the last build on a branch.
I've added this one to speed up builds when jarsigning practically blocked work.

**Comment by akurtakov** [comment]
https://ci.eclipse.org/linuxtools/job/linuxtools/job/stable-8.16/3/ should be good. @jjohnstn please verify and contribute to simrel once the build completes.

**Comment by akurtakov** [comment]
Fixed now.
