### ISSUE TITLE
Cleaning up old CI jobs

### ISSUE THREAD

**Issue by fredg02** [eclipse-linuxtools/org.eclipse.linuxtools#440]
Please consider cleaning up old CI jobs on the Linux Tools Jenkins instance.

For example, https://ci.eclipse.org/linuxtools/job/linuxtools/ shows branches that have not been built in more than a year. If you want to store build artifacts permanently, please store them on download.eclipse.org.

cc: @akurtakov

**Comment by fredg02** [comment]
You can exclude the branches in the branch sources configuration here: https://ci.eclipse.org/linuxtools/job/linuxtools/configure

Branches `stable-8.6`, `stable-8.7`, `stable-8.8`, `stable-8.9` are only kept around since one of the builds is marked as `keep forever`.

**Comment by akurtakov** [comment]
Thanks for the guidance. Builds are no longer marked to keep for ever and jenkins did it cleanup. What's left is simply not garbage collected as there are no other builds to clean up. Please reopen with more details what I've missed if there is smth pending.

**Comment by fredg02** [comment]
I've reduced `Max # of old items to keep` from 5 to 1 in the branch source config to remove the remaining branches that were not cleaned up. If a branch is excluded, it should actually be removed despite this setting. I'd consider this a bug in the Multi-branch source plugin.

**Comment by fredg02** [comment]
Thanks for cleaning up! :+1:
