### ISSUE TITLE
The 'docker-compose.exe' command could not be located in 'C:\Program Files\Docker Toolbox'

### ISSUE THREAD

**Issue by gr0l** [eclipse-linuxtools/org.eclipse.linuxtools#69]
When trying to use the docker compose integration of the Docker Tooling under Windows 10 with installed Docker for Desktop 4+ only a messagebox with the error "The 'docker-compose.exe' command could not be located in 'C:\Program Files\Docker Toolbox'" appears.

The docker-compse.exe is deprecated in newer Docker versions and are integrated in the docker command. 
Instead of using `docker-compose.exe` the command `docker compose` should be used.

**Comment by akurtakov** [comment]
Current developers don't have Windows machines so what do you think about contributing a fix for that?

**Comment by akurtakov** [comment]
I'll take that lack of activity as no interest from anyone to implement this.
